export enum ParentActions {
  UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT",
  UPDATE_SELECTED_PARENT = "UPDATE_SELECTED_PARENT"
}

export enum DragonActions {
  SET_FIRST_PARENT = "SET_FIRST_PARENT",
  SET_SECOND_PARENT = "SET_SECOND_PARENT"
}
